from pathlib import Path

DATA_ROOT = Path("_data")

# Training Data
TRAINING_ROOT_PATH = DATA_ROOT / "training"
TRANING_SOURCE_PATH = TRAINING_ROOT_PATH / "source"
TRAINING_IMAGE_PATH = TRAINING_ROOT_PATH / "images"
TRAINING_DATA_FILE_PATH = TRAINING_ROOT_PATH / "training_data.parquet"
# Region Detection
REGION_DETECTION_PATH = TRAINING_ROOT_PATH / "region_detection"
REGION_DETECTION_TRAINING_PATH = REGION_DETECTION_PATH / "train"
REGION_DETECTION_TRAINING_IMAGE_PATH = REGION_DETECTION_TRAINING_PATH / "image"
REGION_DETECTION_TRAINING_LABEL_PATH = REGION_DETECTION_TRAINING_PATH / "label"
REGION_DETECTION_VALIDATION_PATH = REGION_DETECTION_PATH / "val"
REGION_DETECTION_VALIDATION_IMAGE_PATH = REGION_DETECTION_VALIDATION_PATH / "image"
REGION_DETECTION_VALIDATION_LABEL_PATH = REGION_DETECTION_VALIDATION_PATH / "label"

# Validation Data
VALIDATION_ROOT_PATH = DATA_ROOT / "validation"
VALIDATION_SOURCE_PATH = VALIDATION_ROOT_PATH / "source"
VALIDATION_IMAGE_PATH = VALIDATION_ROOT_PATH / "images"
VALIDATION_DATA_FILE_PATH = VALIDATION_ROOT_PATH / "validation_data.parquet"

# Model Training
# Paths
MODEL_OUTPUT_PATH = DATA_ROOT / "output"
CARD_FRAME_CLASSIFIER_MODEL_PATH = MODEL_OUTPUT_PATH / "classifier"
REGION_DETECTOR_MODEL_PATH = MODEL_OUTPUT_PATH / "regional_detector"
