"""
Train YOLO11n-OBB for card boundary detection.

Uses synthetic training data generated by generate_card_detection_data.py.
Detects a single class ("card") with oriented bounding boxes.

Usage:
    python scripts/train_card_detector.py
    python scripts/train_card_detector.py --epochs 150 --batch-size 64
"""

import sys
from pathlib import Path

import _resolve  # noqa: F401

import argparse
import logging

import torch
from ultralytics import YOLO

import config

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    handlers=[logging.StreamHandler()],
)
logger = logging.getLogger(__name__)


def train_card_detector(
    data_yaml_path: Path,
    output_path: Path,
    model_size: str = "yolo11n-obb.pt",
    num_epochs: int = 100,
    batch_size: int = 64,
    image_size: int = 640,
    patience: int = 15,
    learning_rate: float = 0.001,
    learning_rate_final: float = 0.01,
    weight_decay: float = 0.0005,
) -> Path:
    """
    Train YOLO11n-OBB model for card boundary detection.

    Single-class detection with oriented bounding boxes -- the model
    learns to find the card quadrilateral in a phone photo.

    Args:
        data_yaml_path: Path to YOLO OBB dataset config (data.yaml).
        output_path: Directory to save trained model.
        model_size: YOLO-OBB model variant.
        num_epochs: Training epochs.
        batch_size: Batch size (RTX 5090 can handle 64+ for nano).
        image_size: Input image size.
        patience: Early stopping patience.
        learning_rate: Initial learning rate.
        learning_rate_final: Final LR ratio for cosine annealing.
        weight_decay: L2 regularization.

    Returns:
        Path to the best model weights.
    """
    logger.info("=" * 60)
    logger.info("CARD BOUNDARY DETECTOR TRAINING")
    logger.info("=" * 60)
    logger.info(f"Model:      {model_size}")
    logger.info(f"Epochs:     {num_epochs}")
    logger.info(f"Batch size: {batch_size}")
    logger.info(f"Image size: {image_size}")
    logger.info(f"LR:         {learning_rate}")
    logger.info(f"Patience:   {patience}")
    logger.info(f"Data:       {data_yaml_path}")
    logger.info(f"Output:     {output_path}")

    if not data_yaml_path.exists():
        raise FileNotFoundError(f"Data YAML not found: {data_yaml_path}")

    output_path.mkdir(parents=True, exist_ok=True)

    device = 0 if torch.cuda.is_available() else "cpu"
    if torch.cuda.is_available():
        logger.info(f"GPU: {torch.cuda.get_device_name(0)}")

    # Load pretrained YOLO-OBB model
    model = YOLO(model_size)
    logger.info(f"Loaded {model_size}")

    # Train
    model.train(
        data=str(data_yaml_path.resolve()),
        epochs=num_epochs,
        batch=batch_size,
        imgsz=image_size,
        patience=patience,
        save=True,
        project=str(output_path.resolve()),
        name="card_detector",
        exist_ok=True,
        pretrained=True,
        optimizer="AdamW",
        lr0=learning_rate,
        lrf=learning_rate_final,
        weight_decay=weight_decay,
        warmup_epochs=3,
        warmup_momentum=0.8,
        warmup_bias_lr=0.1,
        plots=True,
        device=device,
        # Augmentation -- YOLO built-in augmentations for robustness
        hsv_h=0.015,
        hsv_s=0.5,
        hsv_v=0.3,
        degrees=15.0,
        translate=0.1,
        scale=0.3,
        fliplr=0.0,  # Cards are not horizontally symmetric in a meaningful way
        flipud=0.0,
        mosaic=0.5,  # Mosaic helps with multi-card scenes
        mixup=0.1,
    )

    # Validate
    metrics = model.val()
    logger.info(f"Final mAP50:    {metrics.box.map50:.4f}")
    logger.info(f"Final mAP50-95: {metrics.box.map:.4f}")

    best_path = output_path / "card_detector" / "weights" / "best.pt"

    # Copy best.pt to output root so config.CARD_DETECTION_MODEL_PATH / "best.pt" works
    import shutil
    top_level_best = output_path / "best.pt"
    if best_path.exists():
        shutil.copy2(best_path, top_level_best)
        logger.info(f"Copied best model to {top_level_best}")

    logger.info(f"Best model: {best_path}")
    logger.info("=" * 60)

    return top_level_best


def main():
    parser = argparse.ArgumentParser(description="Train card boundary detector")
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--batch-size", type=int, default=64)
    parser.add_argument("--image-size", type=int, default=640)
    parser.add_argument("--patience", type=int, default=15)
    parser.add_argument("--lr", type=float, default=0.001)
    parser.add_argument("--model", type=str, default="yolo11n-obb.pt",
                        help="YOLO model variant (e.g. yolo11n-obb.pt, yolo11n-pose.pt)")
    parser.add_argument("--task", choices=["obb", "keypoint"], default="obb",
                        help="obb: oriented bounding box, keypoint: 4-corner keypoint detection")
    args = parser.parse_args()

    if args.task == "keypoint":
        data_yaml = config.CARD_DETECTION_DATASET_PATH.parent / "dataset_keypoint" / "data.yaml"
        output_path = config.CARD_DETECTION_MODEL_PATH.parent / "card-detector-keypoint"
        model = args.model if "pose" in args.model else "yolo11n-pose.pt"
    else:
        data_yaml = config.CARD_DETECTION_DATASET_PATH / "data.yaml"
        output_path = config.CARD_DETECTION_MODEL_PATH
        model = args.model

    train_card_detector(
        data_yaml_path=data_yaml,
        output_path=output_path,
        model_size=model,
        num_epochs=args.epochs,
        batch_size=args.batch_size,
        image_size=args.image_size,
        patience=args.patience,
        learning_rate=args.lr,
    )


if __name__ == "__main__":
    main()
